name: bigclipper
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.30.0
  - numpy=1.20.3
  - python=3.9.5
  - scipy=1.6.3
  - pip=21.1.3
  - pysam=0.16.0.1
  - pip:
    - argparse==1.4.0
